### ISSUE TITLE
Getting 429 error Accessing ChatGPT API via MATLAB

### ISSUE THREAD

**Issue by Kallol-Biswas** [toshiakit/MatGPT#13]
![image](https://github.com/toshiakit/MatGPT/assets/52074701/c8d31fa5-57db-4ce7-8eae-c7ab520b3369)

**Comment by Kallol-Biswas** [comment]
Hello Sir , whenever I am trying to use MATGPT, I am getting this error. I would appreciate your suggestions in this regard. thank you

**Comment by nothans** [comment]
Check your OpenAI API key. Is it correctly stored? Is it shared? Is it still active in your OpenAI account?

**Comment by toshiakit** [comment]
Most probably because your free trial expired. Check your account and if this is the case, you have to pay.
