### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by yanndebray** [toshiakit/MatGPT#20]
Before starting a new chat, I'd like to be able to access the settings in order to enter my API key for instance.
You can keep a chat specific settings page for each new chat, but I would like a "default" setting, that could be accessed from a button on the top right of the app looking like this:
![image](https://github.com/toshiakit/MatGPT/assets/128002745/c578cb79-0be0-402d-98c3-5fef852124df)

**Comment by toshiakit** [comment]
There is a new update in the 'dev' branch that streamline the process to add your API key.

**Comment by nothans** [comment]
Try the latest release. We just merged dev into main and cut a new release (v2.0.0).
