### ISSUE TITLE
Can the new version of MatGPT streamingly receive the responses from LLM?
If not, how can we realize it?

### ISSUE THREAD

**Issue by huliangbing** [toshiakit/MatGPT#25]

**Comment by toshiakit** [comment]
This is a duplicate of #23 How to streamingly receive replies from a large model using Matlab? 
Please see my answer there.

**Comment by huliangbing** [comment]
Thank you very much!
I will have a try using matlab.net.http.io.StringConsumer.

**Comment by toshiakit** [comment]
This feature is added in LLMs with MATLAB.

**Comment by huliangbing** [comment]
Thanks a lot!

**Comment by toshiakit** [comment]
This is supported in 2.0.1
