### ISSUE TITLE
Insufficient_quota error

### ISSUE THREAD

**Issue by farid-zare** [toshiakit/MatGPT#27]
Hi, 
I am using three different openAI accounts, which all have API credit, however MatGPT is responding "Insufficient_quota" from two days ago for all the accounts.
I would be greatly appreciate it if you can help me through this.
Regards,

**Comment by toshiakit** [comment]
Check this forum thread and see if this applies to you. https://community.openai.com/t/429-error-insufficient-quota/492350
MatGPT cannot fix the issues you have with OpenAI account.

**Comment by farid-zare** [comment]
Thank you very much for your response. It was a billing problem for my openAI account.
