### ISSUE TITLE
JSON syntax error

### ISSUE THREAD

**Issue by xixici** [toshiakit/MatGPT#31]
When I flip the switch for streaming responses, I encounter an error message saying, `"JSON syntax error: expected "" but found end of text."`

Has anyone else run into this problem? Is there a way to fix it?

![image](https://github.com/toshiakit/MatGPT/assets/11867924/556b988e-ef01-4475-8524-36aaf94ca8ea)

**Comment by toshiakit** [comment]
This is caused by OpenAI API returning an incomplete json data during streaming. There is nothing we can do from the client side, but we plan to improve the error message in order to make the cause clearer. This only occurs intermittently.
