### ISSUE TITLE
beginner's question :)

### ISSUE THREAD

**Issue by djeronimoBiH** [toshiakit/MatGPT#40]
It's probably something trivial and it's probably my fault, but I need your help: I ​​get this error when I want to start a new Chat in MatGPT: Undefined function 'openAIChat' for input arguments of type 'string'.

Thank you.

**Comment by toshiakit** [comment]
Hi, the error message indicates that you haven't installed "LLMs with MATLAB" library. https://www.mathworks.com/matlabcentral/fileexchange/163796-large-language-models-llms-with-matlab

You can install it using Add-on Explorer in the Home tab of MATLAB , and search for "Large Language Models with MATLAB"

![1688381359108](https://github.com/toshiakit/MatGPT/assets/1530470/3cd8e689-1ca6-4989-92e2-83237c0da8f2)
