### ISSUE TITLE
baby steps on MatGPT

### ISSUE THREAD

**Issue by mogfor0g** [toshiakit/MatGPT#42]
Hey,

I’d like to know how I can obtain API access to use the software for my studies in order to assist with MATLAB assignments, solve complex equations, and enhance my learning experience. I’d appreciate it if you could provide access or point me in the right direction to get API to use your app to do so.

Thanks,
mogfor0g

**Comment by toshiakit** [comment]
If you are unfamiliar with using API, I recommend using [AI Chat Playground instead](https://www.mathworks.com/matlabcentral/playground/)
