### ISSUE TITLE
Error message in Matlab

### ISSUE THREAD

**Issue by Francisco84929495** [toshiakit/MatGPT#43]
Excuse my ignorance, but I am trying to learn how these codes work. When I type in Matlab the command:

git clone https://github.com/toshiakit/MatGPT.git

I get the following message:

Unrecognized function or variable 'git'.

Any help available?

Franz

**Comment by xixici** [comment]
Please verify your Git environment.

**Comment by Francisco84929495** [comment]
Thank you.
