### ISSUE TITLE
Error with MatGPT

### ISSUE THREAD

**Issue by RafeyTahir** [toshiakit/MatGPT#6]
![MatGPT](https://user-images.githubusercontent.com/109905807/231307815-f64743be-6296-4f7f-bcb7-2ae28118195d.png)
Sir i'm using MatGPT on Matlab R2021b and its giving me this type of error (see attached pic) every time. Do we need ChatGPT Plus account or it will run on the free account as well?

**Comment by toshiakit** [comment]
Thank you for posting this. This is an unknown issue caused when the API key is not valid. Please make sure you set up the valid API key in the environment variable.

**Comment by DANAJK** [comment]
> Thank you for posting this. This is an unknown issue caused when the API key is not valid. Please make sure you set up the valid API key in the environment variable.

I set my API key correctly (I think) and still got this message. It was fixed by setting up payments in my OpenAI account. (The free credits I had received at the start had expired).

**Comment by toshiakit** [comment]
@DANAJK thank you, that makes sense. This is caused by API returning 401 error, which could either mean the API key is not valid or the free trial has expired.
